# Enable nice!view
CONFIG_ZMK_DISPLAY=y
# Enable custom display
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
# CONFIG_NICE_VIEW_DISP_ROTATE_180=y
# Disable idle blanking
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n
