# Enable mouse emulation.
# CONFIG_ZMK_POINTING=y

# Change idle settings
CONFIG_ZMK_IDLE_TIMEOUT=15000

# Deep sleep settings
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# BLE connection speed tuning
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=200

# Increase BLE TX power for more reliable connection
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Custom keyboard name (max. 16 characters)
CONFIG_ZMK_KEYBOARD_NAME="Splitty"
